### ISSUE TITLE
Why is this not written in Rust?

### ISSUE THREAD

**Issue by girotobial** [moritonal/UnityAsyncSystem#1]
## *Who* is the bug affecting?
Me, Bobby

## *What* is affected by this bug?
The very fabric of the universe

## *When* does this occur?
When i read the code

## *Where* on the platform does it happen?
All files

## *How* do we replicate the issue?
You don't

## Expected behavior (i.e. solution)
All code in Rust

## Other Comments
BASIC also acceptable.

**Comment by moritonal** [comment]
Can't fix until https://arewegameyet.rs/ is true ;)
